ENCODING = "utf-8"
PEER_ID_PREFIX = b'-PT0010-'
BLOCK_SIZE = 2 ** 14
PROTOCOL_NAME = b'BitTorrent protocol'
HANDSHAKE_LEN = 68
UDP_PROTOCOL_ID = 0x41727101980

MIN_BLOCKS_PER_CYCLE = 8
BLOCKS_PER_CYCLE = MIN_BLOCKS_PER_CYCLE

CHOKE = 0
UNCHOKE = 1
INTERESTED = 2
NOT_INTERESTED = 3
HAVE = 4
BITFIELD = 5
REQUEST = 6
PIECE = 7
CANCEL = 8

EMPTY_RESPONSE_THRESHOLD = 5